version: '1.0.{build}'
configuration:
- Release
image:
- Visual Studio 2017
platform: Any CPU
init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
before_build:
- cmd: dotnet --version
- nuget sources add -name Shared -source https://ci.appveyor.com/nuget/ems-shared-ddrf9y0xta28
- appveyor-retry dotnet restore -v Minimal

test: off
build_script:
- dotnet -d build -c %CONFIGURATION%
- dotnet test /p:Version=%APPVEYOR_BUILD_VERSION% test/EMS.DataAccess.EntityFrameworkCore.Tests/EMS.DataAccess.EntityFrameworkCore.Tests.csproj --test-adapter-path:. --logger:Appveyor
- dotnet -d pack -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: src\EMS.DataAccess.EntityFrameworkCore\bin\Release\*.nupkg

cache:
